### ISSUE TITLE
Sign up - Insert Information to DB

### ISSUE THREAD

**Issue by saifun** [TechnionYP5779/team1-Social-Geha#20]

**Comment by saifun** [comment]
![image](https://user-images.githubusercontent.com/44426592/55465003-eeeedc00-5604-11e9-8cd8-3c3158e7d138.png)

**Comment by ofiralexi** [comment]
The screen is already implemented #12 
Try to gather all the API functions of the DB in one Java class (like ServerAPI class)

**Comment by YarinSh** [comment]
Because DB functions are all running on a different task, in order to use onSuccess ,onFailure and onComplete some functions will need to be in the activity class file (because I would like to implement a different behavior on different calls, and I need the calling activity's context and intents), but I will try to keep the DB functions as separate as possible - to the possible degree.
